openapi: 3.0.0
info:
  title: StreamX API
  version: 1.0.0
  description: API para gerenciamento de contas, usuários e filmes
servers:
  - url: http://localhost:4000
    description: Servidor local

tags:
  - name: Accounts
    description: Gerenciamento de contas e autenticação
  - name: Users
    description: Operações com usuários
  - name: Movies
    description: Gerenciamento de filmes

paths:
  /account:
    post:
      tags:
        - Accounts
      summary: Cria uma nova conta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: Conta criada com sucesso
        400:
          description: Dados inválidos
        500:
          description: Erro interno do servidor

  /auth:
    post:
      tags:
        - Accounts
      summary: Realiza login e gera token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login realizado com sucesso
        400:
          description: Requisição mal formatada ou erro no token
        401:
          description: Credenciais inválidas
        404:
          description: Conta não encontrada
        500:
          description: Erro interno

  /users:
    get:
      tags:
        - Users
      summary: Lista todos os usuários
      responses:
        200:
          description: Lista de usuários
        500:
          description: Erro interno

    post:
      tags:
        - Users
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        201:
          description: Usuário criado
        500:
          description: Erro interno

  /users/{id}:
    get:
      tags:
        - Users
      summary: Busca um usuário específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Usuário encontrado
        400:
          description: ID inválido
        404:
          description: Usuário não encontrado
        500:
          description: Erro interno

    put:
      tags:
        - Users
      summary: Atualiza um usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: Usuário atualizado
        400:
          description: ID inválido
        500:
          description: Erro interno

    delete:
      tags:
        - Users
      summary: Remove um usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Usuário deletado
        400:
          description: ID inválido
        500:
          description: Erro interno

  /movies:
    get:
      tags:
        - Movies
      summary: Lista todos os filmes
      responses:
        200:
          description: Lista de filmes
        500:
          description: Erro interno

    post:
      tags:
        - Movies
      summary: Cadastra um novo filme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - year
                - rate
                - duration
                - genre
              properties:
                title:
                  type: string
                year:
                  type: integer
                rate:
                  type: string
                duration:
                  type: integer
                genre:
                  type: string
                extraInformation:
                  type: array
                  items:
                    type: object
                    properties:
                      director:
                        type: string
                      movie_rating:
                        type: number
                      synopsis:
                        type: string
      responses:
        201:
          description: Filme criado
        500:
          description: Erro interno

  /movies/{id}:
    get:
      tags:
        - Movies
      summary: Busca um filme específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Filme encontrado
        400:
          description: ID inválido
        404:
          description: Filme não encontrado
        500:
          description: Erro interno

    put:
      tags:
        - Movies
      summary: Atualiza um filme existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                year:
                  type: integer
                rate:
                  type: string
                duration:
                  type: integer
                genre:
                  type: string
                extraInformation:
                  type: array
                  items:
                    type: object
                    properties:
                      director:
                        type: string
                      movie_rating:
                        type: number
                      synopsis:
                        type: string
      responses:
        200:
          description: Filme atualizado
        400:
          description: ID inválido
        500:
          description: Erro interno

    delete:
      tags:
        - Movies
      summary: Remove um filme
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Filme removido
        400:
          description: ID inválido
        500:
          description: Erro interno
